CREATE TABLE files(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    imgFilename CHAR(32) NOT NULL UNIQUE,
    thumbFilename CHAR(32) NOT NULL UNIQUE,
    parentId INTEGER REFERENCES files(id)
);

CREATE TABLE tags(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE fileTags(
    tagId INTEGER NOT NULL REFERENCES tags(id),
    fileId INTEGER NOT NULL REFERENCES files(id),
    UNIQUE (tagId, fileId)
);

CREATE TABLE users(
    user VARCHAR(255) NOT NULL UNIQUE,
    password CHAR(32) NOT NULL
);
